# Generated by Django 5.0.3 on 2024-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_remove_label_tasks'),
        ('tasks', '0005_alter_task_author_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='labels.label', verbose_name='tasks'),
        ),
    ]
