# Generated by Django 5.0.3 on 2024-04-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
    ]
